services:
  python:
    build:
      context: .
    environment:
      ENV_NAME: ${CONDA_ENV}
    volumes:
      - ./:/code
      - ../KantarData:/KantarData

    command:  >
      sh -c "python main.py"

    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: ${PQ_PW}


  adminer:
    image: adminer
    restart: always
    depends_on:
      - python
    ports:
      - 8080:8080
  #pgadmin:
  #  image: dpage/pgadmin4
  #  restart: always
  #  ports:
  #    - "8888:80"
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
  #    PGADMIN_DEFAULT_PASSWORD: strong-password
  #  depends_on:
  #    - python
