name: kantar_data_env2
channels:
  - anaconda
  - anaconda-fusion
  - defaults
  - conda-forge
dependencies:
  - python>=3.12
  - openpyxl
  - ipykernel
  - ipython
  - jupyter
  - pandas
  - seaborn
  - sqlalchemy=2.0.25
  - sqlalchemy-utils=0.41.1
  - statsmodels
  - tqdm
  - numpy
  #- nbconvert>=7.10
  - psycopg2
